export enum Role {
  TEAM_MEMBER = 1,
  CHALLENGE_MEMBER = 2,
  JEDI_PARTNER = 3,
  JEDI_FREERANGE = 4,
  DELEGATE = 5,
  USER = 6,
  CREW = 8,
  TEAM_LEAD = 101,
  CHALLENGE_LEAD = 102,
  DELEGATE_LEAD = 105,
  TRACK_MAYOR = 108
}
