export enum WidgetEnum {
  LOGIN = 'LOGIN',
  EXPLORE = 'EXPLORE',
  BUY_NFT = 'BUY_NFT',
  GO_TO = 'GO_TO', // TODO rename to ACTION_BUTTON
  MY_PROFILE = 'MY_PROFILE',
  CREATOR = 'CREATOR',
  STAKING = 'STAKING',
  STAKING_VIEW = 'STAKING_VIEW',
  USER_DETAILS = 'USER_DETAILS',
  WORLD_DETAILS = 'WORLD_DETAILS',
  WORLD_VISITORS = 'WORLD_VISITORS',
  WORLD_PROFILE = 'WORLD_PROFILE',
  VOICE_CHAT = 'VOICE_CHAT',
  OBJECT = 'OBJECT',
  NEWSFEED = 'NEWSFEED',
  TIMELINE = 'TIMELINE',
  MUSIC = 'MUSIC',

  ACTION = 'ACTION',

  MOVE_ITEM = 'MOVE_ITEM',
  INSPECTOR = 'INSPECTOR',
  ASSIGN_FUNCTIONALITY = 'ASSIGN_FUNCTIONALITY',
  REMOVE = 'REMOVE',
  DUPLICATE = 'DUPLICATE'
}
