export enum WidgetEnum {
  LOGIN = 'LOGIN',
  EXPLORE = 'EXPLORE',
  PROFILE = 'PROFILE',
  STAKING_OVERVIEW = 'STAKING_OVERVIEW',
  WORLD_OVERVIEW = 'WORLD_OVERVIEW',
  UNIVERSE_INFO = 'UNIVERSE_INFO'
}
