export const ROUTES = {
  base: '/',
  login: '/login',
  loginEmail: '/loginEmail',
  loginWeb3: '/web3/login',
  web3: '/web3',
  consentWeb3: '/web3/consent',
  storyBook: '/system/storybook',
  signUpComplete: '/profile/signUpComplete',
  callBack: '/oidc/callback',
  web3CallBack: '/oidc/web3/callback',
  spaceDashboard: '/dashboard/space/:id',
  spaceAdmin: '/space/:spaceId/admin',
  collaboration: '/collaboration',
  stageMode: '/collaboration/stage-mode',
  dashboard: '/collaboration/dashboard',
  calendar: '/collaboration/calendar',
  screenShare: '/collaboration/screenshare',
  miro: '/collaboration/miro',
  googleDrive: '/collaboration/google-drive',
  createSpace: '/profile?createspace=1',
  magic: '/magic/:key',
  worldCalendar: '/calendar',
  help: '/help'
};
